In [25]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
books = []
rating_map = {
    "One":1, "Two":2, "Three":3, "Four":4, "Five":5
}

for page in range(1, 11):   
    url = f"http://books.toscrape.com/catalogue/page-{page}.html"
    response = requests.get(url)
    soup = BeautifulSoup(response.text, "html.parser")
    for book in soup.find_all("article", class_="product_pod"):
        title = book.h3.a["title"]
        price = book.find("p", class_="price_color").text
        price = price.replace("£", "")   
        availability = book.find("p", class_="instock availability").text.strip()    
        rating = book.p["class"][1]
        rating = rating_map.get(rating, 0)
        books.append({
            "Title": title,
            "Price": price,
            "Availability": availability,
            "Rating": rating
        })
print(f"Total records scraped: {len(books)}")
df = pd.DataFrame(books)
df.to_csv("books_data.csv", index=False)

print("Data saved successfully!")

Total records scraped: 200
Data saved successfully!

In [26]:
df

,Title,Price,Availability,Rating
0,A Light in the Attic,Â51.77,In stock,3
1,Tipping the Velvet,Â53.74,In stock,1
2,Soumission,Â50.10,In stock,1
3,Sharp Objects,Â47.82,In stock,4
4,Sapiens: A Brief History of Humankind,Â54.23,In stock,5
...,...,...,...,...
195,Eureka Trivia 6.0,Â54.59,In stock,4
196,Drive: The Surprising Truth About What Motivat...,Â34.95,In stock,4
197,Done Rubbed Out (Reightman & Bailey #1),Â37.72,In stock,5
198,Doing It Over (Most Likely To #1),Â35.61,In stock,3
199,Deliciously Ella Every Day: Quick and Easy Rec...,Â42.16,In stock,3

In [27]:
import time
time.sleep(1)

In [22]:
rating_text = book.p["class"][1]

rating_map = {
    "One":1, "Two":2, "Three":3, "Four":4, "Five":5
}

Rating = rating_map.get(rating_text, 0)

In [30]:
df

,S.No,Title,Price,Availability,Rating
0,1,A Light in the Attic,Â51.77,In stock,3
1,2,Tipping the Velvet,Â53.74,In stock,1
2,3,Soumission,Â50.10,In stock,1
3,4,Sharp Objects,Â47.82,In stock,4
4,5,Sapiens: A Brief History of Humankind,Â54.23,In stock,5
...,...,...,...,...,...
195,196,Eureka Trivia 6.0,Â54.59,In stock,4
196,197,Drive: The Surprising Truth About What Motivat...,Â34.95,In stock,4
197,198,Done Rubbed Out (Reightman & Bailey #1),Â37.72,In stock,5
198,199,Doing It Over (Most Likely To #1),Â35.61,In stock,3
199,200,Deliciously Ella Every Day: Quick and Easy Rec...,Â42.16,In stock,3

In [29]:
df.insert(0, "S.No", range(1, len(df) + 1))